package com.example.group52.configuration;

import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

import org.h2.server.web.JakartaWebServlet;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import jakarta.annotation.PostConstruct;

@Configuration
@ConditionalOnProperty(prefix = "spring.h2.console", name = "enabled", havingValue = "true")
public class H2ConsoleConfiguration {

    private static final Logger log = LoggerFactory.getLogger(H2ConsoleConfiguration.class);

    @Value("${spring.h2.console.path:/h2-console}")
    private String consolePath;

    @Value("${spring.datasource.url:jdbc:h2:mem:testdb}")
    private String datasourceUrl;

    @Value("${spring.datasource.username:sa}")
    private String datasourceUser;

    @Bean
    public ServletRegistrationBean<JakartaWebServlet> h2ConsoleServlet() {
        String mapping = consolePath.endsWith("/*") ? consolePath : (consolePath + "/*");
        ServletRegistrationBean<JakartaWebServlet> registration =
                new ServletRegistrationBean<>(new JakartaWebServlet(), mapping);
        registration.setLoadOnStartup(1);
        return registration;
    }

    @PostConstruct
    public void preloadConsoleDefaults() {
        try {
            Path propsFile = Path.of(System.getProperty("user.home"), ".h2.server.properties");
            Properties props = new Properties();
            props.setProperty("0",
                    "Group52 (File)|org.h2.Driver|" + datasourceUrl + "|" + datasourceUser);
            props.setProperty("webAllowOthers", "false");
            props.setProperty("webPort", "8082");
            props.setProperty("webSSL", "false");
            try (OutputStream out = Files.newOutputStream(propsFile)) {
                props.store(out, "H2 Server Properties — auto-generated by Group52");
            }
            log.info("Wrote H2 console defaults to {}", propsFile);
        } catch (Exception ex) {
            log.warn("Could not write H2 console defaults: {}", ex.getMessage());
        }
    }
}
