spring.application.name=group52

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=/h2-console
spring.main.allow-bean-definition-overriding=true
spring.devtools.restart.exclude=**/database/**,**/*.mv.db,**/*.trace.db,**/*.lock.db,**/bin/**,**/build/**,**/.gradle/**,**/.idea/**,**/.vscode/**
# spring.devtools.restart.enabled=false
logging.level.org.springframework.boot.devtools=DEBUG
# app|browser
app.launch.mode=app
# popup|tab
app.course.open-mode=popup


# Change ur datasource in here as well to whatever
# ur own keys here not ours :P
spring.ai.google.genai.api-key=

spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=